stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-west-2"

build:
  image: python:3.11
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
    - pip install boto3 requests -t ./package
  script:
    - cp -r services main.py package/
    - cd package && zip -r ../embedding-api.zip .
  artifacts:
    paths:
      - embedding-api.zip
    expire_in: 1 hour
  only:
    - main

deploy:
  image: amazon/aws-cli:2.13.6
  stage: deploy
  script:
    - echo "DEBUG: CI/CD variable LAMBDA_CODE_BUCKET = $LAMBDA_CODE_BUCKET"
    - echo "DEBUG: Listing directory contents"
    - ls -lh
    - echo "DEBUG: Inspecting zip file"
    - if [ -f embedding-api.zip ]; then file embedding-api.zip; else echo "❌ embedding-api.zip not found"; fi
    - echo "DEBUG: Starting upload to S3..."
    - aws s3 cp embedding-api.zip s3://$LAMBDA_CODE_BUCKET/lambda-code/embedding-api.zip
    - echo "DEBUG: Updating Lambda..."
    - aws lambda update-function-code --function-name embedding-api-lambda \
      --s3-bucket $LAMBDA_CODE_BUCKET \
      --s3-key lambda-code/embedding-api.zip
  dependencies:
    - build
  only:
    - main
