stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-west-2"

build:
  image: python:3.11
  stage: build
  before_script:
    - apt-get update && apt-get install -y zip
    - pip install boto3 requests -t ./package
  script:
    - cp -r services main.py package/
    - cd package && zip -r ../embedding-api.zip .
  artifacts:
    paths:
      - embedding-api.zip
    expire_in: 1 hour
  only:
    - main

deploy:
  image: amazon/aws-cli:2.13.6
  stage: deploy
  script:
    - ls -lh
    - if [ -f embedding-api.zip ]; then file embedding-api.zip; else echo "❌ embedding-api.zip not found"; fi
    - printenv

  dependencies:
    - build
  only:
    - main
