stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-west-2"

deploy:
  image: amazon/aws-cli:2.13.6  # ✅ AWS CLI + zip included
  stage: deploy
  before_script:
    - yum install -y zip python3-pip
    - pip3 install -r requirements.txt -t ./package
  script:
    - cp -r services main.py package/
    - cd package && zip -r ../embedding-api.zip .
    - aws s3 cp embedding-api.zip s3://$LAMBDA_CODE_BUCKET/lambda-code/embedding-api.zip
    - aws lambda update-function-code --function-name embedding-api-lambda \
      --s3-bucket $LAMBDA_CODE_BUCKET \
      --s3-key lambda-code/embedding-api.zip
  only:
    - main