stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: "eu-west-2"

deploy:
  image: python:3.11
  stage: deploy
  before_script:
    - pip install boto3 requests
  script:
    - pip install -r requirements.txt -t ./package
    - cp -r services main.py package/
    - cd package && zip -r ../embedding-api.zip .
    - aws s3 cp embedding-api.zip s3://$LAMBDA_CODE_BUCKET/lambda-code/embedding-api.zip
    - aws lambda update-function-code --function-name embedding-api-lambda \
      --s3-bucket $LAMBDA_CODE_BUCKET \
      --s3-key lambda-code/embedding-api.zip
  only:
    - main
